name: 'Docker 6.0 '

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 21 * *'

jobs:
  call-common-workflow:
    uses: ./.github/workflows/docker-dynare-common.yml
    with:
      matlab_release: "R2023b"
      dynare_release: "6.0"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
