name: Dynare 5.5 MATLAB R2023b

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dynare_5_5_matlab_r2023b:
    uses: ./.github/workflows/dynare-testsuite-common.yml
    with:
      dynare-version: "5.5"
      testsuite: "matlab"
    secrets:
      matlab-licensefile-base64: ${{ secrets.MATLAB_LICENSEFILE_BASE64 }}