name: Dynare 6.0 Octave 8.4.0

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dynare_6_0_octave_8_4_0:
    uses: ./.github/workflows/dynare-testsuite-common.yml
    with:
      dynare-version: "6.0"
      testsuite: "octave"
    secrets:
      matlab-licensefile-base64: ${{ secrets.MATLAB_LICENSEFILE_BASE64 }}