name: 'Testsuite Dynare 5.5 (Octave 6.4.0) '

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # At 00:00 on Monday

jobs:
  dynare_5_5_octave_6_4_0:
    uses: ./.github/workflows/testsuite-dynare-common.yml
    with:
      dynare-version: "5.5"
      testsuite: "octave"
    secrets:
      matlab-licensefile-base64: ${{ secrets.MATLAB_LICENSEFILE_BASE64 }}
      matlab-LNUCreds-info-base64: ${{ secrets.LNUCREDS_INFO_BASE64 }}