name: 'Testsuite Dynare 5.1 (MATLAB R2022a) '

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # At 00:00 on Monday

jobs:
  dynare_5_1_matlab_r2022a:
    uses: ./.github/workflows/testsuite-dynare-common.yml
    with:
      dynare-version: "5.1"
      testsuite: "matlab"
    secrets:
      matlab-licensefile-base64: ${{ secrets.MATLAB_LICENSEFILE_BASE64 }}