name: 'Testsuite Dynare 5.3 (MATLAB R2022b) '

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # At 00:00 on Monday

jobs:
  dynare_5_3_matlab_r2022b:
    uses: ./.github/workflows/testsuite-dynare-common.yml
    with:
      dynare-version: "5.3"
      testsuite: "matlab"
    secrets:
      matlab-licensefile-base64: ${{ secrets.MATLAB_LICENSEFILE_BASE64 }}