name: 'Testsuite 8.4.0 ' # name will be used in table of badges in README.md

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # At 00:00 on Monday

jobs:
  dynare_6_0_octave_8_4_0:
    uses: ./.github/workflows/testsuite-dynare-common.yml
    with:
      dynare-version: "6.0"
      testsuite: "octave"
    secrets:
      matlab-licensefile-base64: ${{ secrets.MATLAB_LICENSEFILE_BASE64 }}