name: 'Testsuite Dynare 5.0 (MATLAB R2021b) '

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # At 00:00 on Monday

jobs:
  dynare_5_0_matlab_r2021b:
    uses: ./.github/workflows/testsuite-dynare-common.yml
    with:
      dynare-version: "5.0"
      testsuite: "matlab"
    secrets:
      matlab-licensefile-base64: ${{ secrets.MATLAB_LICENSEFILE_BASE64 }}
      matlab-LNUCreds-info-base64: ${{ secrets.LNUCREDS_INFO_BASE64 }}