name: 'Testsuite Dynare 4.6.4 (MATLAB R2021a) '

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # At 00:00 on Monday

jobs:
  dynare_4_6_4_matlab_r2021a:
    uses: ./.github/workflows/testsuite-dynare-common.yml
    with:
      dynare-version: "4.6.4"
      testsuite: "matlab"
    secrets:
      matlab-licensefile-base64: ${{ secrets.MATLAB_LICENSEFILE_BASE64 }}