name: 'Testsuite Dynare 5.0 (Octave 5.2.0) '

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # At 00:00 on Monday

jobs:
  dynare_5_0_octave_5_2_0:
    uses: ./.github/workflows/testsuite-dynare-common.yml
    with:
      dynare-version: "5.0"
      testsuite: "octave"
    secrets:
      matlab-licensefile-base64: ${{ secrets.MATLAB_LICENSEFILE_BASE64 }}