name: 'Testsuite Dynare 5.4 (Octave 5.2.0) '

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # At 00:00 on Monday

jobs:
  dynare_5_4_octave_5_2_0:
    uses: ./.github/workflows/testsuite-dynare-common.yml
    with:
      dynare-version: "5.4"
      testsuite: "octave"
    secrets:
      matlab-licensefile-base64: ${{ secrets.MATLAB_LICENSEFILE_BASE64 }}